/* Economy checks shared by deterministic VM and real browser. */
function economyChecks(check) {
  function freshEconomy() {
    easy=true; reset(); running=true; ore=1000; nextWave=enemySpawn=9999; enemyScoutSent=true;
  }
  function stepEconomy(seconds) { for(let i=0;i<seconds*20&&!ended;i++) update(.05); }
  freshEconomy();
  check(materials===0 && nodes.filter(n=>n.kind==='materials').length===3, 'Three finite material deposits; player starts with none');
  check(!resourceObserved(nodes.find(n=>n.kind==='materials'&&n.x===1260)), 'Enemy deposit inventory is hidden without scouting');
  let deposit=nodes.find(n=>n.kind==='materials'&&n.x===275);
  const worker=alive(0).find(u=>u.type==='worker');
  check(!canHarvest(worker,deposit), 'Materials cannot be extracted without a completed supplied quarry');
  check(!validBuild({x:600,y:1030},'quarry') && validBuild(deposit,'quarry'), 'Quarries must occupy a deposit');
  selected=[worker]; build('factory');
  check(!placing && materials===0 && ore===1000, 'Artillery Works cannot be ordered without Materials');
  build('quarry'); command({x:deposit.x+8,y:deposit.y});
  const quarry=alive(0).find(u=>u.type==='quarry');
  check(quarry && quarry.x===deposit.x && quarry.y===deposit.y && quarry.construction>0 && ore===900, 'Quarry snaps to deposit and pays Supplies');
  check(!quarryFor(deposit,0), 'Unfinished quarry cannot extract Materials');
  stepEconomy(25);
  check(!quarry.construction && quarryFor(deposit,0)===quarry, 'Worker constructs and connects a quarry');
  const miners=alive(0).filter(u=>u.type==='worker').slice(0,2);
  miners.forEach(w=>issueOrder(w,{kind:'gather',node:deposit}));
  stepEconomy(40);
  check(materials>0 && deposit.amount<1600, 'Provisioners physically extract and deliver Materials');
  const raider=add('trooper',1,300,775); rebuildSupply();
  check(!supplied(quarry) && !canHarvest(worker,deposit), 'Raider cuts quarry supply and stops extraction');
  raider.hp=0; rebuildSupply();
  check(supplied(quarry), 'Clearing the route restores quarry extraction');
  quarry.hp=0; rebuildSupply();
  check(!quarryFor(deposit,0) && !canHarvest(worker,deposit), 'Destroying a quarry stops further extraction');
  freshEconomy();
  deposit=nodes.find(n=>n.kind==='materials'&&n.x===275); deposit.amount=5;
  add('quarry',0,deposit.x,deposit.y); rebuildSupply();
  const carrier=alive(0).find(u=>u.type==='worker');
  carrier.x=deposit.x+53; carrier.y=deposit.y; carrier.carrying=0; carrier.harvest=0;
  issueOrder(carrier,{kind:'gather',node:deposit});
  stepEconomy(16);
  check(materials===5 && deposit.amount===0, 'Final partial Materials load is delivered exactly once');
  freshEconomy();
  const cache=nodes.find(n=>!n.kind);
  const workers=alive(0).filter(u=>u.type==='worker');
  workers.forEach((w,i)=>{w.x=cache.x+30;w.y=cache.y;w.carrying=0;w.harvest=0;issueOrder(w,{kind:'gather',node:cache});});
  check(workers.filter(w=>canHarvest(w,cache)).length===2, 'A supply cache has two simultaneous extraction slots');
  deposit=nodes.find(n=>n.kind==='materials'&&n.x===275); add('quarry',0,deposit.x,deposit.y); rebuildSupply();
  workers.forEach(w=>{w.x=deposit.x+53;w.y=deposit.y;issueOrder(w,{kind:'gather',node:deposit});});
  check(workers.filter(w=>canHarvest(w,deposit)).length===3, 'A quarry has three simultaneous extraction slots');
  freshEconomy(); materials=100;
  const school=alive(0).find(u=>u.type==='forge'); school.hp=0;
  selected=[alive(0).find(u=>u.type==='core')]; build('factory');
  check(!placing && ore===1000 && materials===100, 'Completed Guard School is required before Artillery Works');
  add('forge',0,465,920); build('factory'); command({x:480,y:1080});
  const lab=alive(0).find(u=>u.type==='factory');
  check(lab && ore===760 && materials===50, 'Factory construction pays both resources');
  cancelConstruction(lab);
  check(ore===940 && materials===87.5, 'Cancelled construction refunds 75% of both resources');
  freshEconomy();
  const factory=add('factory',0,500,1080); selected=[factory];
  train('walker'); check(factory.queue.length===0 && ore===1000, 'Artillery recruitment requires Materials');
  materials=25; train('walker');
  check(factory.queue[0]==='walker' && materials===0 && ore===840, 'Artillery costs 160 Supplies and 25 Materials');
  cancelRecruit(factory,0);
  check(materials===25 && ore===1000, 'Recruit cancellation refunds both resources in full');
  materials=59; startResearch('shells');
  check(!factory.research && materials===59, 'Shell research requires 60 Materials');
  materials=60; startResearch('shells'); cancelResearch(factory);
  check(materials===45 && ore===955, 'Research cancellation returns 75% of both resources');
  freshEconomy();
  const first=alive(0).find(u=>u.type==='forge'),second=add('forge',0,560,1020);
  rebuildSupply();
  selected=[first,second]; train('trooper'); train('trooper');
  check(first.queue.length===1 && second.queue.length===1, 'Repeated recruitment distributes across selected production buildings');
  first.research={id:'drill',progress:0}; train('scout');
  check(first.queue.length===1 && second.queue.length===2, 'Recruitment skips researching producers');
  const funds=ore; selected=[alive(1).find(u=>u.type==='forge')]; train('trooper');
  check(ore===funds, 'Enemy producers cannot spend player funds');
  freshEconomy();
  const idle=alive(0).find(u=>u.type==='worker'); idle.order={kind:'hold'};
  selectIdleWorkers();
  check(selected.length===1 && selected[0]===idle, 'Idle command selects idle provisioners only');
  freshEconomy();
  const enemyStart=enemyMaterials; stepEconomy(40);
  check(enemyMaterials>enemyStart, 'Rhino workers deliver Materials to their economy');
  enemyMaterials=0; wave=2; enemySpawn=t;
  const gunsBefore=alive(1).filter(u=>u.type==='walker').length; enemyThink();
  check(alive(1).filter(u=>u.type==='walker').length===gunsBefore, 'Rhino army cannot produce guns without Materials');
  reset(); check(materials===0 && enemyMaterials===60, 'Restart resets both Materials economies');
}
