const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {run,tick}=require('./smoke.cjs');
run(fs.readFileSync(path.join(__dirname,'../dist/field-guide.js'),'utf8'));
run('$("guide-enabled").checked=true;$("guide-action").dataset={};reset();running=true;nextWave=enemySpawn=9999;updateFieldGuide(true)');
assert.equal(run('fieldGuideAdvice(fieldGuideFacts()).id'),'supplies');
assert.equal(run('guideProgress.startUid'),run('uid'));
assert(!run('paused'),'adviser leaves simulation running');
tick(600);run('updateFieldGuide(true)');
assert(run('guideProgress.done.includes("supplies")'),'only physical delivery completes first lesson');
assert.equal(run('fieldGuideAdvice(fieldGuideFacts()).id'),'recruit');
run('selected=[alive(0).find(u=>u.type==="forge")];train("trooper")');tick(200);run('updateFieldGuide(true)');
assert(run('guideProgress.done.includes("recruit")'),'completed paid reinforcement detected');
run('const guideScout=add("scout",0,300,800);updateFieldGuide(true)');
assert(!run('guideProgress.done.includes("scout")'),'map knowledge alone does not count as scouting');
run('guideScout.x=depot.x;guideScout.y=depot.y;updateFieldGuide(true)');
assert(run('guideProgress.done.includes("scout")'),'scout personally reaches depot sight range');
run('alive(0).filter(u=>u.type==="worker").forEach(u=>u.hp=0)');
assert.equal(run('fieldGuideAdvice(fieldGuideFacts()).kind'),'core','worker losses require recruiting replacements');
run('$("guide-enabled").checked=false;reset();running=true;updateFieldGuide(true)');
assert(run('!guideProgress.enabled&&$("guide-toggle").hidden'),'new battle opt-out is respected');
console.log('PASS: field adviser delivery/recruitment evidence, real scout sight, recovery, reset, opt-out and no forced pause.');
