// Generate a release fingerprint and complete, project-relative offline inventory.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
function inventory(dir='dist') {
  return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?inventory(path.join(dir,e.name)):[path.join(dir,e.name)])
    .filter(p=>!['sw.js','offline-files.js'].includes(path.basename(p))&&!path.basename(p).startsWith('.')).sort();
}
const files=inventory();
const hash=crypto.createHash('sha256');
for(const f of files)hash.update(f).update(fs.readFileSync(f));
const body='// Generated by node scripts/pwa-cache.cjs; do not edit.\nself.OFFLINE_RELEASE='+JSON.stringify(hash.digest('hex').slice(0,20))+';\nself.OFFLINE_FILES='+JSON.stringify(files.map(f=>'./'+f.slice(5)),null,2)+';\n';
if(process.argv.includes('--check')){
  if(fs.readFileSync('dist/offline-files.js','utf8')!==body)throw Error('Offline inventory stale: run node scripts/pwa-cache.cjs');
  console.log('PASS: offline inventory fingerprints every deployed client file');
}else fs.writeFileSync('dist/offline-files.js',body);
